# Dictionaries

## Storing Data

In the last mission, we worked with a data set that stores information for 7,197 mobile apps.

The `cont_rating` column offers information about the content rating of each app. The content rating of an app (also known as the maturity rating) represents the age required to use that app. The table below shows the unique content ratings in our data set, along with the number of apps specific to each rating:

| **Content rating** | **Number of apps** |
| :--- | :--- |
| 4+ | 4,433 |
| 9+ | 987 |
| 12+ | 1,155 |
| 17+ | 622 |

From the table above, we can see that:
- Most apps (4,433) have a content rating of `4+` (only people aged four or older are allowed to use these apps).
- Apps with a content rating of `17+` are the fewest (622 apps).
- In the middle we have the `9+` and `12+` apps -- 987 apps have a content rating of `9+`, and 1,155 apps have a content rating of `12+`.

If we wanted to save the data from the table above, we could use two lists or maybe a list of lists. We'll try this in the following exercise, while on the next we'll learn about **dictionaries** and explore a more efficient solution for storing the data above.

---
### Instructions

1. Store the data in the table above using two different list.
- Assign the list `['4+', '9+', '12+', '17+']` to a variable named `content_ratings`.
- Assign the list `[4433, 987, 1155, 622]` to a variable named `nums`.
2. Store the data in the table above using a list of lists. Assign the list `[['4+', '9+', '12+', '17+'], [4433, 987, 1155, 622]]` to a variable named `content_rating_numbers`.

In [1]:
content_ratings = ['4+', '9+', '12+', '17+']
nums = [4433, 987, 1155, 622]

content_rating_numbers = [['4+', '9+', '12+', '17+'],
                         [4433, 987, 1155, 622]]

---
## Dictionaries

Above, we saw a table that shows the unique content ratings in our data set, along with the number of apps specific to each rating:

| **Content rating** | **Number of apps** |
| :--- | :--- |
| 4+ | 4,433 |
| 9+ | 987 |
| 12+ | 1,155 |
| 17+ | 622 |

We stored the data above in two ways:
- Using two separate lists
- Using a single list of lists

In [3]:
# Two lists
content_ratings = ['4+', '9+', '12+', '17+']
numbers = [4433, 987, 1155, 622]

# A list of lists
content_rating_numbers = [['4+', '9+', '12+', '17+'],
                         [4433, 987, 1155, 622]]

Looking at the lists above, it may not be immediately clear which content rating corresponds to which number -- especially for someone who doesn't have enough context. We need to find a better way to map a content rating to its corresponding number.

Remember that each list element has an index number. Let's consider the `numbers` list.

What if we could transform the index numbers to content rating values? This way, the mapping between content ratings and their corresponding numbers should become much clearer. Fortunately, we can do this using a **dictionary**:

In [4]:
content_ratings = {'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}
print(content_ratings)

{'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}


To create the dictionary above, we:

- Mapped each content rating to its corresponding number by following an `index:value pattern`. For instance, to map a rating of **'4+'** to the number 4,433, we typed `'4+': 4433` (notice the colon between `'4+'` and `4433`). To map '9+' to 987, we typed '**9+'**: 987, and so on.
- Typed the entire sequence of `index:value` pairs, and separated each with a comma: `'4+': 4433, '9+': 987, '12+': 1155, '17+': 622`.
- Surrounded the sequence with curly braces: `{'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}`


---
### Instructions

1. Map content ratings to their corresponding numbers by recreating the dictionary above: `{'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}`. Assign the dictionary to a variable named `content_ratings`.
2. Print `content_ratings`.

In [5]:
content_ratings = {'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}
print(content_ratings)

{'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}


---
## Indexing

Using a dictionary allowed us to change the index numbers of a list to content rating values. That way, the mapping between content ratings and their corresponding numbers became much clearer.

To retrieve the individual values of the `content_ratings` dictionary, we can use the new indices. The way we retrieve individual dictionary values is identical to the way we retrieve individual list elements -- we follow a **`variable_name[index]`** pattern:

In [7]:
numbers = [4433, 987, 1155, 622]
print(numbers[0])
print(numbers[2])

4433
1155


In [8]:
content_ratings = {'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}
print(content_ratings['4+'])
print(content_ratings['12+'])

4433
1155


---
### Instructions

1. Retrieve the values from the `content_ratings` dictionary.
- Assign the value at index `'9+'` to a variable named `over_9`.
- Assign the value at index `'17+'` to a variable named `over_17`.
2. Print `over_9` and `over_17`.

In [9]:
content_ratings = {'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}

over_9 = content_ratings['9+']
over_17 = content_ratings['17+']
print(over_9)
print(over_17)

987
622


---
## Alternative Way of Creating a Dictionary

Previously, we learned that in order to create a dictionary, we need to:

- Map each index to it's corresponding value by following an `index:value` pattern (e.g. `'4+': 4433`).
- Type the entire sequence of `index:value` pairs, and separate each pair with a comma (e.g. `'4+': 4433, '9+': 987, '12+': 1155, '17+': 622`).
- Surround the sequence with curly braces (e.g. `{'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}`).

Alternatively, we can create a dictionary and populate it with values by following these steps:

1. We create an empty dictionary.
2. We add values one by one to that empty dictionary.

Adding a value to a dictionary follows the pattern **`dictionary_name[index] = value`**. To add a value `4433` with an index `'4+'` to a dictionary named `content_ratings`, we need to use the code `content_ratings['4+'] = 4433`.

In [10]:
content_ratings = {}
content_ratings['4+'] = 4433

print(content_ratings)

{'4+': 4433}


We can keep adding values using this same approach:

In [11]:
content_ratings = {}
content_ratings['4+'] = 4433
content_ratings['9+'] = 987
content_ratings['12+'] = 1155
content_ratings['17+'] = 622

print(content_ratings)

{'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}


At a high level, this approach is identical to populating an empty list by using the `list_name.append()` command. The syntax is different, but fundamentally we take the same steps:

1. We create an empty dictionary (or list).
2. We add values using the `dictionary_name[index] = value` technique (or the `list_name.append()` command in case of a list).